### ISSUE TITLE
Kompletterande bug av issue #45, #46, #47

### ISSUE THREAD

**Issue by SossioG** [SossioG/Syp2-MyHappyPlants#57]
Det finns 8 av 25 tester som ej passerade, gällande upprepa password. 
Lösningsförslag som löser detta:

0. Skapa branch till issue.
2. Gå till Klassen Verifier.java
3. Efter rad 46, lägg till detta:     
    if (!loginInfoToCompare[2].equals(loginInfoToCompare[3])) {
           Platform.runLater(() -> MessageBox.display(BoxTitle.Error, "Please enter the same password twice."));
           return false;
    }
3. Commita Issue och då är testen löst!

**Comment by ecspresso** [comment]
@SossioG Finns det någon klass som testar detta?

**Comment by ecspresso** [comment]
Se issue, avklarat.
